version: '3.8'
services:
  db:
    image: postgres
    container_name : my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: payments
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata://var/lib/postgresql/data

  app:
    image: payments_demo
    container_name: payments_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      POSTGRES_PASS: ${POSTGRES_PASS}
    command: [ "java", "-jar", "app.jar" ]
volumes:
  my_dbdata: